#
# © ООО «Лаборатория 50», 2014, 2015
#
---
    - name: установка dnsmasq
      apt: pkg=dnsmasq state=latest

    - name: создание конфигурационного файла dnsmasq
      template: src=dnsmasq.conf.j2 dest=/etc/dnsmasq.conf backup=yes owner=dnsmasq mode=0644

    - name: добавление hostnames целевых машин в /etc/hosts
      lineinfile: dest=/etc/hosts regexp='.*{{ item.ip }}' line='{{ item.ip }} {{ item.hostname }}' state=present
      with_items: target_machines
      when: target_machines is defined

    - name: очистка dhcp.leases
      file: path=/var/lib/misc/dnsmasq.leases state=absent
      tags: [remove_dhcp_leases]

    - name: перезапуск службы dnsmasq
      service: name=dnsmasq state=restarted
      tags: remove_dhcp_leases
